name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo "DB_HOST=${{vars.DB_HOST}}\nDB_PORT=${{vars.DB_PORT}}\nDB_USER=${{vars.DB_USER}}\nDB_PASS=${{vars.DB_PASS}}\nDB_NAME=${{vars.DB_NAME}}" > .env  
        docker compose up
