name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: 
      name: development
    env: 
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASS: ${{ vars.DB_PASS }}
      DB_NAME: ${{ vars.DB_NAME }}

    steps:
    - uses: actions/checkout@v4
    - name: test environment variables
      run: |
        echo "DB_HOST=$DB_HOST
        DB_PORT=$DB_PORT
        DB_USER=$DB_USER
        DB_PASS=$DB_PASS
        DB_NAME=$DB_NAME" >> .env
        docker compose up
