name: Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
#  test:
#    runs-on: ubuntu-latest
#   steps: 
#      - uses: actions/checkout@v4
 #     
  #    - uses: actions/setup-node@v4.0.2
   #     name: run tests
    #    with: 
     #     node-version: 16
      #- run: |
       #   npm ci
        #  npm run test

  build:
    runs-on: ubuntu-latest
    environment: 
      name: development
    env: 
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASS: ${{ vars.DB_PASS }}
      DB_NAME: ${{ vars.DB_NAME }}
    steps:
      - name: build Docker conteiners
        uses: actions/checkout@v4
      - run: docker compose up
      - name: Stop Containers
        if: always()
        run: docker-compose -f "docker-compose.yaml" down


