name: Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    environment: 
      name: development
    env: 
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASS: ${{ vars.DB_PASS }}
      DB_NAME: ${{ vars.DB_NAME }}

    steps:
    - name: check code 
      uses: actions/checkout@v4

    - name: run tests
      uses: actions/setup-node@v4
      with: 
          node-version: 16
    - run: |
        npm ci
        npm run test

    - name: build Docker conteiners
      run: |
        echo "DB_HOST=$DB_HOST
        DB_PORT=$DB_PORT
        DB_USER=$DB_USER
        DB_PASS=$DB_PASS
        DB_NAME=$DB_NAME" >> .env
        docker compose up -d --build

    - name: stop conteiners
      run: docker compose down
    

